---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    project_root: "{{ playbook_dir }}/../.."
    kind_cluster_name: newsbrief-dev
    registry_name: kind-registry
    registry_port: 5000
    dev_namespace: newsbrief-dev
    prod_namespace: newsbrief-prod
    caddy_container_name: newsbrief-proxy
